/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'link' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'technologies' : IDL.Vec(IDL.Text),
});
export const SocialLinks = IDL.Record({
  'dev' : IDL.Text,
  'linkedin' : IDL.Text,
  'twitter' : IDL.Text,
  'email' : IDL.Text,
  'stackOverflow' : IDL.Text,
  'internetComputer' : IDL.Text,
  'github' : IDL.Text,
});
export const PortfolioData = IDL.Record({
  'bio' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'socialLinks' : SocialLinks,
  'name' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getPortfolioData' : IDL.Func([], [PortfolioData], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'link' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'technologies' : IDL.Vec(IDL.Text),
  });
  const SocialLinks = IDL.Record({
    'dev' : IDL.Text,
    'linkedin' : IDL.Text,
    'twitter' : IDL.Text,
    'email' : IDL.Text,
    'stackOverflow' : IDL.Text,
    'internetComputer' : IDL.Text,
    'github' : IDL.Text,
  });
  const PortfolioData = IDL.Record({
    'bio' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'socialLinks' : SocialLinks,
    'name' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getPortfolioData' : IDL.Func([], [PortfolioData], []),
  });
};

export const init = ({ IDL }) => { return []; };